exclude:
  - './.git'
  - './.github'
  - './assets'
  - './data'
  - './deployment'
  - './docs'
  - './pegasus'
  - './scripts'
  - './sharegpt'
  - './spitfight'
  - './tests'
  - './.gitignore'
  - './_config.yml'
  - './app.py'
  - './LICENSE'
  - './README.md'
  - './requirements.txt'
  - './setup.py'
