models:
  - name: bigscience/bloom-560m
    instances:
      - ip_address: worker0
        port: 8001
        docker_port: 8000
        device: '"device=0"'
        num_shard: 1
  - name: tiiuae/falcon-7b-instruct
    instances:
      - ip_address: worker1
        port: 8002
        docker_port: 8000
        device: '"device=1"'
        num_shard: 1


